export const resturantData = [
    {
        "id": 1, 
        "name": "Cabanos", 
        "category": "meats", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it", 
        "website": "http://cabanos.ca", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 2, 
        "name": "Chica's Nashville Hot Chicken", 
        "category": "meats", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it", 
        "website": "https://www.chicaschicken.net/order/", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 3, 
        "name": "Kansas King", 
        "category": "meats", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it", 
        "website": "https://www.kansasking.com/menus", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {   
        "id": 4, 
        "name": "XXI Chophouse", 
        "category": "meats", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it", 
        "website": "https://www.xxichophouse.com/dinner", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 5, 
        "name": "Wow! Wing House", 
        "category": "meats", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it", 
        "website": "http://www.wowwinghouse.com/morningside-milner/", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 6, 
        "name": "Top Gun Burger", 
        "category": "meats", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it", 
        "website": "http://www.topgunburgerto.com/menu/", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 7, 
        "name": "The Captain's Boil", 
        "category": "seafood", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it", 
        "website": "https://thecaptainsboil.com/locations/", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 8, 
        "name": "Goodfellas Wood Stove Pizza", 
        "category": "pizza", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it", 
        "website": "", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 9, 
        "name": "Papa Giuseppes", 
        "category": "pizza", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it", 
        "website": "", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 10,
        "name": "KyKy Kookies", 
        "category": "dessert", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it",  
        "website": "https://www.kykykookies.com/", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 11,
        "name": "Holy Shakes", 
        "category": "food-truck", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it",  
        "website": "https://416-food-truck-company.square.site/", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 12,
        "name": "August 8", 
        "category": "seafood", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it",  
        "website": "http://august8.ca/", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 13,
        "name": "Kaka", 
        "category": "seafood", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it",  
        "website": "http://kakaallyoucaneat.ca/", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    },
    {
        "id": 14,
        "name": "Barsa", 
        "category": "tapas", 
        "description": "Aliyah's take: here I put the information that I would want my date or friends to hear about this place and my fav things about it",  
        "website": "https://barsataberna.com/", 
        "bg-pic": "", 
        "phone": "",
        "location": "", 
    }   
]; 